root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/__ProjectName__"
  cmd = "go build -ldflags=\"-X 'main.version=dev'\" -o ./tmp/__ProjectName__ ./cmd/__ProjectName__"
  delay = 500
  exclude_dir = ["tmp", "testdata", ".git", ".beans", "node_modules"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "html"]
  kill_delay = 500

[log]
  time = false

[misc]
  clean_on_exit = true
