// SPDX-License-Identifier: MIT

// Package app is the project's shell: it owns the layout templates,
// the homepage, the compiled Tailwind CSS bundle, and the project-wide
// icon defines. Following Pattern B (see burrow docs/guide/tailwind.md),
// the shell lives in a single internal package so all embedded assets
// sit next to the code that uses them.
package app

import (
	"embed"
	"html/template"
	"io/fs"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oliverandrich/burrow"
	"github.com/oliverandrich/burrow/contrib/messages"
)

//go:embed templates
var templateFS embed.FS

// all:static so the placeholder .gitkeep is included; the real
// app.min.css is generated by `mise run css` and lives alongside it
// (gitignored — see .gitignore).
//
//go:embed all:static
var staticFS embed.FS

// App implements the shell app.
type App struct{}

// New creates a new shell app.
func New() *App { return &App{} }

func (a *App) Name() string { return "app" }

// FuncMap returns template functions used by the layout templates.
func (a *App) FuncMap() template.FuncMap {
	return template.FuncMap{
		"alertClass": func(level messages.Level) string {
			return string(level)
		},
	}
}

// TemplateFS returns the embedded HTML template files.
func (a *App) TemplateFS() fs.FS {
	sub, _ := fs.Sub(templateFS, "templates")
	return sub
}

// StaticFS serves the embedded `static/` under the URL prefix
// `/static/app/`, mirroring how every Burrow contrib namespaces its
// assets (htmx → /static/htmx/..., admin → /static/admin/..., etc.).
func (a *App) StaticFS() (string, fs.FS) {
	sub, _ := fs.Sub(staticFS, "static")
	return "app", sub
}

func (a *App) NavItems() []burrow.NavItem {
	return []burrow.NavItem{
		{Label: "Home", URL: "/", Icon: "app/icon_home", Position: 1},
	}
}

func (a *App) Routes(r chi.Router) {
	r.Get("/", burrow.Handle(home))
}

func home(w http.ResponseWriter, r *http.Request) error {
	return burrow.Render(w, r, http.StatusOK, "pages/home", map[string]any{"Title": "Home"})
}
